### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mouldybread**
Added English translation of template.yaml

### CODE REVIEW

**Comment by z1022** [comment]
Screenshot 2023-07-30 223221
follow the Installation but config error.  Don't know what wrong

**Comment by aes-alienrip** [comment]
Apologies for the Late Reply.🙏
I am not expecting someone making a pull request and surprisingly to see english user to use my fork😁
In the latest release i embedded both apparent temperature and uv index sensor into js file and made it translatable from lovelace's setting.
The English translation referred to [hko weather icons](https://www.hko.gov.hk/textonly/v2/explain/wxicon_e.htm) and i had made 2 changes to shorten the text when considering the width of lovelace.

- Sunny Periods with A Few Showers -> Light Showers
- Sunny Intervals with Showers -> Showers

Please feel free to comment if you have any other ideas.

**Comment by AzNdevil** [comment]
thanks for the card, looks really good!
would be nice to be able to see typhoon related info as well

anyways....im not sure where to put this since i cant seem to report issues for this repo

1. the install guide does not match the current package downloaded from hacs, i manually added the rest.yaml and template.yaml entries and got it to work
2. hko_wind_speed and hko_wind_gust sometimes returns blank in the csv causing error messages in homeassistant.log

`ValueError: Sensor sensor.hko_wind_gust has device class 'wind_speed', state class 'None' unit 'km/h' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
2023-09-05 19:12:41.592 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rest platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''`

replacing the sensor code in rest.yaml with below fixes the error

`{% if is_number(ns.s) %}
          {{ ns.s }}
        {% else %}
          {{ 0 }}
        {% endif %}`

**Comment by aes-alienrip** [comment]
> thanks for the card, looks really good! would be nice to be able to see typhoon related info as well
> 
> anyways....im not sure where to put this since i cant seem to report issues for this repo
> 
> 1. the install guide does not match the current package downloaded from hacs, i manually added the rest.yaml and template.yaml entries and got it to work
> 2. hko_wind_speed and hko_wind_gust sometimes returns blank in the csv causing error messages in homeassistant.log
> 
> `ValueError: Sensor sensor.hko_wind_gust has device class 'wind_speed', state class 'None' unit 'km/h' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>) 2023-09-05 19:12:41.592 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rest platform for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state numerical_value = int(value) ^^^^^^^^^^ ValueError: invalid literal for int() with base 10: ''`
> 
> replacing the sensor code in rest.yaml with below fixes the error
> 
> `{% if is_number(ns.s) %} {{ ns.s }} {% else %} {{ 0 }} {% endif %}`

Thanks for reporting and  i had enabled the issues feature in setting and updated the rest.yaml in latest release.
Yeah i am preparing to add the [warnsum](https://www.hko.gov.hk/tc/wservice/warning/details.htm) but also finding how to add to the card looks better, such as using HKO original icons for all warning or, placing warnings other than typhoon in slot section.
Here is my self-made typhoon svg
tc8nwltc8nwc

**Comment by AzNdevil** [comment]
maybe something like a png to svg converter? https://new.express.adobe.com/tools/convert-to-svg
and manually cleaning up the colors afterwards?

sorry i am useless at anything related to graphics or trying to make things looks nice

anyways keep up the great work and thanks for updating!

**Pull request closed without merging**
